### ISSUE TITLE
exec: "/app/podsync": stat /app/podsync: no such file or directory: unknown

### ISSUE THREAD

**Issue by klopp1991** [tuxpeople/docker-podsync#96]
Hi together

I have following error. Can anyone help me?

`"starting container failed: OCI runtime create failed: container_linux.go:367: starting container process caused: exec: "/app/podsync": stat /app/podsync: no such file or directory: unknown"`

My Dockercompose
`[...]
volumes:
      - /var/lib/docker/volumes/PodsyncConfig/_data/:/app
[...]

**Comment by tuxpeople** [comment]
@klopp1991 I'm very sorry for the long time without an answer.

The problem is, the app is located in `/app/podsync`. If you mount a volume/folder at `/app`, everything previously in `/app` will disappear. Therefore, after mounting the volume, `/app/podsync` cant be found anymore. You need to bind-mount only the config file. Here's my compose podsync snippet as an example:

```yaml
  podsync:
    container_name: podsync
    image: tdeutsch/podsync:latest
    restart: unless-stopped
    logging:
      driver: json-file
      options:
        max-file: ${DOCKERLOGGING_MAXFILE}
        max-size: ${DOCKERLOGGING_MAXSIZE}
    labels:
      - org.hotio.pullio.update=${PULLIO_UPDATE}
      - org.hotio.pullio.notify=${PULLIO_NOTIFY}
      - org.hotio.pullio.discord.webhook=${PULLIO_DISCORD_WEBHOOK}
    ports:
      - 8888:8080
    environment:
      PUID: ${PUID}
      PGID: ${PGID}
      TZ: ${TZ}
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${DOCKERCONFDIR}/podsync/config.toml:/app/config.toml:ro
      - ${DOCKERSTORAGEDIR}/media/podcasts:/data
    healthcheck:
      test: wget http://localhost:8080 -qO /dev/null || exit 1
      interval: 1m30s
      timeout: 10s
      retries: 3
```

Hope this helps. Let me know.
